// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen/v2 version v2.2.0 DO NOT EDIT.
package api

// UserInput defines model for UserInput.
type UserInput struct {
	Name string `json:"name" validate:"required"`
}

// UserResponse defines model for UserResponse.
type UserResponse struct {
	Id   int    `json:"id"`
	Name string `json:"name"`
}

// UserId defines model for userId.
type UserId = int

// CreateUserJSONRequestBody defines body for CreateUser for application/json ContentType.
type CreateUserJSONRequestBody = UserInput
